services:
  # tor:
  #   image: tor:$TOR_VERSION
  #   build:
  #     context: ./tor
  #     args:
  #       - TOR_VERSION=$TOR_VERSION
  #       - TOR_USER_ID=$TOR_USER_ID
  #       - GROUP_ID=$SHARED_GID
  #   volumes:
  #     - $TOR_DATA:/home/tor
  #   restart: on-failure
  #   networks:
  #     default:
  #       ipv4_address: 172.18.0.2
  # i2p:
    # image: i2p:$I2P_VERSION
    # profiles:
    #   - disabled
    # build:
    #   context: ./i2p
    #   args:
    #     - I2P_VERSION=$I2P_VERSION
    #     - I2P_USER_ID=$I2P_USER_ID
    #     - GROUP_ID=$SHARED_GID
    # volumes:
    #   - $I2P_DATA:/i2p/.i2p
    # environment:
    #   - EXT_PORT:7656
    # ports:
    #   - 7657:7657
    # restart: on-failure
    # networks:
    #   default:
    #     ipv4_address: 172.18.0.3
  bitcoind:
    image: bitcoind:$BITCOIN_VERSION
    build:
      context: ./bitcoind
      args:
        - BITCOIN_VERSION=$BITCOIN_VERSION
        - BITCOIN_USER_ID=$BITCOIN_USER_ID
        - GROUP_ID=$SHARED_GID
    volumes:
      - $BITCOIN_DATA:/home/bitcoin/.bitcoin
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.4
    # Add this to fix permissions before starting bitcoind
    user: root
    entrypoint: >
      bash -c "chown -R bitcoin:bitcoin /home/bitcoin/.bitcoin &&
      su -c 'bitcoind -chain=$$BITCOIN_NETWORK' bitcoin"
    environment:
      - BITCOIN_NETWORK=${BITCOIN_NETWORK:-testnet4}
  electrs:
    image: electrs:$ELECTRS_VERSION
    depends_on:
      - bitcoind
    build:
      context: ./electrs
      args:
        - ELECTRS_VERSION=$ELECTRS_VERSION
        - ELECTRS_USER_ID=$ELECTRS_USER_ID
        - GROUP_ID=$SHARED_GID
    volumes:
      - $BITCOIN_DATA:/home/electrs/.bitcoin
      - $ELECTRS_DATA:/home/electrs/.electrs
    restart: on-failure
    networks:
      default:
        ipv4_address: 172.18.0.5
  # btcrpcexplorer:
  #   image: btcrpcexplorer:$BTC_RPC_EXPLORER_VERSION
  #   depends_on:
  #     - bitcoind
  #     - electrs
  #   build:
  #     context: ./btcrpcexplorer
  #     args:
  #       - BTC_RPC_EXPLORER_VERSION=$BTC_RPC_EXPLORER_VERSION
  #       - BTC_RPC_EXPLORER_USER_ID=$BTC_RPC_EXPLORER_USER_ID
  #       - GROUP_ID=$SHARED_GID
  #   volumes:
  #     - $BTC_RPC_EXPLORER_DATA:/home/btcrpcexplorer/.config
  #   restart: on-failure
  #   networks:
  #     default:
  #       ipv4_address: 172.18.0.6
  # nginx:
  #   image: nginx:alpine-slim
  #   depends_on:
  #     - btcrpcexplorer
  #     - electrs
  #   ports:
  #     - $BTC_RPC_EXPLORER_HTTPS_PORT:3003
  #     - $ELECTRS_SSL_PORT:50002
  #   volumes:
  #     - $NGINX_DATA:/etc/nginx
  #   restart: on-failure
  #   networks:
  #     default:
  #       ipv4_address: 172.18.0.7

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1